SRC=../src

# replace this with your SeqAn include directory
CXXFLAGS+=-I../../seqan-library-2.0.0/include

uname_S := $(shell sh -c 'uname -s 2>/dev/null || echo not')
ifeq ($(uname_S),Linux)
	LFLAGS=-lrt
endif

DEPS = $(SRC)/referenceset.hpp $(SRC)/efficiency.hpp $(SRC)/pairset.hpp $(SRC)/parameters.hpp $(SRC)/localsearch.hpp
OBJ = mopo16s.o referenceset.o efficiency.o pairset.o localsearch.o

default: all
all: mopo16s

mopo16s: $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LFLAGS)

%.o: $(SRC)/%.cpp $(DEPS)
	$(CXX) $(CXXFLAGS) -c -o $@ $< $(LFLAGS)

clean:
	rm -f $(OBJ) mopo16s

.PHONY: default all clean

