SRC=../src
CXXFLAGS+=-I../../seqan-library-2.0.0/include

uname_S := $(shell sh -c 'uname -s 2>/dev/null || echo not')
ifeq ($(uname_S),Linux)
	LFLAGS=-lrt
endif

DEPS = $(SRC)/referenceset.hpp $(SRC)/feasibility.hpp $(SRC)/pairset.hpp $(SRC)/parameters.hpp $(SRC)/localsearch.hpp
OBJ = optprimer.o referenceset.o feasibility.o pairset.o localsearch.o

default: all
all: optprimer

optprimer: $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LFLAGS)

%.o: $(SRC)/%.cpp $(DEPS)
	$(CXX) $(CXXFLAGS) -c -o $@ $< $(LFLAGS)

clean:
	rm -f $(OBJ) optprimer

.PHONY: default all clean

